### ISSUE TITLE
grandpa-ranger can't reconnect to RPC

### ISSUE THREAD

**Issue by 3h4x** [t3rn/t3rn#1017]
## Expected behavior

When there is intermittent network disruption, grandpa ranger should reconnect to RPC endpoints.

### Actual behavior

It's stuck with
```
Starting new range submission loop: 2023-05-25T07:26:23.754Z

    at processTimers (node:internal/timers:514:7)
    at listOnTimeout (node:internal/timers:573:17)
    at Timeout._onTimeout (/app/grandpa-ranger/node_modules/@t3rn/sdk/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:528:182)
    at WsProvider.value (/app/grandpa-ranger/node_modules/@t3rn/sdk/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:406:32)
Error: No response received from RPC endpoint in 60s
```

### Steps to reproduce

Disconnect internet

**Comment by 3h4x** [comment]
Still an issue

**Comment by 3h4x** [comment]
Still an issue

**Comment by 3h4x** [comment]
@coun7zero
