### ISSUE TITLE
rococo-local devnet parachains not collating

### ISSUE THREAD

**Issue by chiefbiiko** [t3rn/t3rn#235]
### Expected behavior
When running the [rococo local devnet](https://github.com/t3rn/t3rn/tree/fix-devnet/docker/xcm-devnet), having set collator keys, [reserved a para id](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#reserve-a-para-id), and [registered a parachain](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#registration-transaction), collators should be blocking after the next relay epoch change.

### Actual behavior

Collators attempt block production but then panic due to a zero division.

#### Logs

[3rrlogs.txt](https://github.com/t3rn/t3rn/files/8169677/3rrlogs.txt)

##### Excerpt

```
t3rn1      | 2022-03-02 12:38:54.024 DEBUG tokio-runtime-worker parachain::approval-distribution: [Relaychain] Processing NewBlocks
t3rn1      | 2022-03-02 12:38:54.025 DEBUG tokio-runtime-worker parachain::approval-distribution: [Relaychain] Got new blocks [(0x2a9a559c289431dcaa36be489078b635cf7496f8a936aa39ba14f57b3281d77e, 42)]
t3rn1      | 2022-03-02 12:38:54.025 DEBUG tokio-runtime-worker multistream_select::negotiated: [Relaychain] Negotiated: Received confirmation for protocol: /dot/sync/2    
t3rn1      | 2022-03-02 12:38:54.025 DEBUG tokio-runtime-worker libp2p_core::upgrade::apply: [Relaychain] Successfully applied negotiated protocol    
t3rn1      | 2022-03-02 12:38:54.025 DEBUG tokio-runtime-worker wasm-heap: [Relaychain] allocator being destroyed, max_total_size 648, max_bumper 1223936    
t3rn1      | 2022-03-02 12:38:54.026 DEBUG tokio-runtime-worker wasm-heap: [Relaychain] allocator being destroyed, max_total_size 2097256, max_bumper 3320632    
t3rn1      | 
t3rn1      | ====================
t3rn1      | 
t3rn1      | Version: 0.1.0
t3rn1      | 
t3rn1      |    0: sp_panic_handler::set::{{closure}}
t3rn1      |    1: std::panicking::rust_panic_with_hook
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:610:17
t3rn1      |    2: std::panicking::begin_panic_handler::{{closure}}
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:500:13
t3rn1      |    3: std::sys_common::backtrace::__rust_end_short_backtrace
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
t3rn1      |    4: rust_begin_unwind
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
t3rn1      |    5: core::panicking::panic_fmt
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
t3rn1      |    6: core::panicking::panic
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:47:5
t3rn1      |    7: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
t3rn1      |    8: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
t3rn1      |    9: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
t3rn1      |   10: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block
t3rn1      |   11: std::panicking::try
t3rn1      |   12: std::thread::local::LocalKey<T>::with
t3rn1      |   13: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
t3rn1      |   14: sc_executor::wasm_runtime::RuntimeCache::with_instance
t3rn1      |   15: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
t3rn1      |   16: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
t3rn1      |   17: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
t3rn1      |   18: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
t3rn1      |   19: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
t3rn1      |   20: <circuit_parachain_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
t3rn1      |   21: sp_api::Core::initialize_block_with_context
t3rn1      |   22: sc_block_builder::BlockBuilder<Block,A,B>::new
t3rn1      |   23: sc_basic_authorship::basic_authorship::Proposer<B,Block,C,A,PR>::propose_with::{{closure}}
t3rn1      |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
t3rn1      |   25: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
t3rn1      |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
t3rn1      |   27: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
t3rn1      |   28: tokio::park::thread::CachedParkThread::block_on
t3rn1      |   29: tokio::runtime::handle::Handle::block_on
t3rn1      |   30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
t3rn1      |   31: tokio::runtime::task::harness::Harness<T,S>::poll
t3rn1      |   32: tokio::runtime::blocking::pool::Inner::run
t3rn1      |   33: std::sys_common::backtrace::__rust_begin_short_backtrace
t3rn1      |   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
t3rn1      |   35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
t3rn1      |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
t3rn1      |       std::sys::unix::thread::Thread::new::thread_start
t3rn1      |              at rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys/unix/thread.rs:106:17
t3rn1      |   36: start_thread
t3rn1      |   37: clone
t3rn1      | 
t3rn1      | 
t3rn1      | Thread 'tokio-runtime-worker' panicked at 'attempt to calculate the remainder with a divisor of zero', /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/ops/arith.rs:584
t3rn1      | 
t3rn1      | This is a bug. Please report it at:
t3rn1      | 
t3rn1      | 	https://github.com/t3rn/t3rn/issues/new
t3rn1      | 
t3rn1      | 2022-03-02 12:38:54.028  INFO tokio-runtime-worker cumulus-collator: [Parachain] Starting collation. relay_parent=0x2a9a559c289431dcaa36be489078b635cf7496f8a936aa39ba14f57b3281d77e at=0xc923ef598545bb59d3c26382befba4f9eb4b75480afb2f207127f2808f26b475
t3rn1      | 2022-03-02 12:38:54.028 DEBUG tokio-runtime-worker wasm_overrides: [Parachain] No WASM override available for block BlockId::Hash(0x2a9a559c289431dcaa36be489078b635cf7496f8a936aa39ba14f57b3281d77e), using onchain code    
t3rn1      | 2022-03-02 12:38:54.029 DEBUG tokio-runtime-worker wasm-heap: [Parachain] allocator being destroyed, max_total_size 112, max_bumper 1223296    
t3rn1      | 2022-03-02 12:38:54.029 DEBUG tokio-runtime-worker wasm_overrides: [Parachain] No WASM override available for block BlockId::Hash(0x2a9a559c289431dcaa36be489078b635cf7496f8a936aa39ba14f57b3281d77e), using onchain code    
t3rn1      | 2022-03-02 12:38:54.029 DEBUG tokio-runtime-worker wasm-heap: [Parachain] allocator being destroyed, max_total_size 112, max_bumper 1223296    
t3rn1      | 2022-03-02 12:38:54.034 DEBUG tokio-runtime-worker wasm_overrides: [Parachain] No WASM override available for block BlockId::Hash(0xc923ef598545bb59d3c26382befba4f9eb4b75480afb2f207127f2808f26b475), using onchain code    
t3rn1      | 2022-03-02 12:38:54.034 DEBUG tokio-runtime-worker aura: [Parachain] Starting authorship at slot 137185394; timestamp = 1646224734029    
t3rn1      | 2022-03-02 12:38:54.034  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent 0xc923ef598545bb59d3c26382befba4f9eb4b75480afb2f207127f2808f26b475    
t3rn1      | 2022-03-02 12:38:54.038 DEBUG tokio-runtime-worker wasm_overrides: [Parachain] No WASM override available for block BlockId::Hash(0xc923ef598545bb59d3c26382befba4f9eb4b75480afb2f207127f2808f26b475), using onchain code    
t3rn1      | 2022-03-02 12:38:54.039  WARN tokio-runtime-worker aura: [Parachain] Proposing failed: ClientImport("RuntimeApiError(Application(Execution(RuntimePanicked(\"attempt to calculate the remainder with a divisor of zero\"))))")    
t3rn1      | 2022-03-02 12:38:54.039 DEBUG tokio-runtime-worker parachain::collation-generation: [Relaychain] collator returned no collation on collate para_id=3000
t3rn1      | 2022-03-02 12:38:54.453  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (1 peers), best: #0 (0xc923…b475), finalized #0 (0xc923…b475), ⬇ 0 ⬆ 0    
t3rn1      | 2022-03-02 12:38:54.454  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (6 peers), best: #42 (0x2a9a…d77e), finalized #39 (0x3121…0daa), ⬇ 2.7kiB/s ⬆ 2.3kiB/s    
t3rn1      | 2022-03-02 12:38:54.456 DEBUG tokio-runtime-worker libp2p_ping::protocol: [Relaychain] Sending pong for [49, 174, 58, 104, 212, 40, 6, 159, 220, 239, 255, 139, 137, 144, 214, 72, 50, 246, 223, 152, 87, 106, 32, 1, 226, 62, 207, 53, 78, 63, 31, 26]    
t3rn1      | 2022-03-02 12:38:54.456 DEBUG tokio-runtime-worker libp2p_ping::protocol: [Relaychain] Waiting for ping ...    
```

### Steps to reproduce

Run:

```
git clone --single-branch --branch fix-devnet --depth 1 git@github.com:t3rn/t3rn.git fix-devnet
cd /fix-devnet/docker/xcm-devnet

mkdir -p ./data/{alice,bob,charlie,dave,eve,t3rn1,t3rn2,pchain1,pchain2}
docker-compose up
```

In another terminal, same directory:

```
pchain1_phrase=$(grep -oP '(?<=phrase:)[^\n]+' ./keys/pchain1.key | xargs)
pchain2_phrase=$(grep -oP '(?<=phrase:)[^\n]+' ./keys/pchain2.key | xargs)
pchain1_adrs=$(grep -oP '(?<=\(SS58\):\s)[^\n]+' ./keys/pchain1.key)
pchain2_adrs=$(grep -oP '(?<=\(SS58\):\s)[^\n]+' ./keys/pchain2.key)

printf "$pchain1_phrase" > ./data/pchain1/chains/local_testnet/keystore/61757261${pchain1_adrs#0x}
printf "$pchain2_phrase" > ./data/pchain2/chains/local_testnet/keystore/61757261${pchain2_adrs#0x}

t3rn1_phrase=$(grep -oP '(?<=phrase:)[^\n]+' ./keys/t3rn1.key | xargs)
t3rn2_phrase=$(grep -oP '(?<=phrase:)[^\n]+' ./keys/t3rn2.key | xargs)

docker exec \
  -u t3rn \
  t3rn1 \
  circuit-collator \
  key \
  insert \
  --base-path /t3rn/data \
  --chain /t3rn/t3rn.raw.json \
  --scheme Sr25519 \
  --suri "$t3rn1_phrase" \
  --key-type aura

docker exec \
  -u t3rn \
  t3rn2 \
  circuit-collator \
  key \
  insert \
  --base-path /t3rn/data \
  --chain /t3rn/t3rn.raw.json \
  --scheme Sr25519 \
  --suri "$t3rn2_phrase" \
  --key-type aura
```

Then connect Polkadot Apps browser UI to `ws://localhost:9944`, using `Alice` [reserve a para id](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#reserve-a-para-id), then [via pallet `parasSudoWrapper` submit extrinsic `sudoScheduleParaInitialize`](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#registration-transaction). The required genesis state and wasm are in the  [`specs` subdirectory](https://github.com/t3rn/t3rn/tree/fix-devnet/docker/xcm-devnet/specs), the parachain id for t3rn is `3000`.

To follow logs of one collator `docker-compose logs -f t3rn1`...

AFAICT collator keys are set up correctly [in the spec](https://raw.githubusercontent.com/t3rn/t3rn/fix-devnet/docker/xcm-devnet/specs/t3rn.json) `.genesis.runtime{.collatorSelection,.session}`.

### Which version(s) does this affect? (Environment, OS, etc...)

Everything in the setup is based on Substrate's v0.9.13 branch.

**Comment by chiefbiiko** [comment]
related to substrate version incompatibilities of our snowfork dependencies - relevant runtime fixes are wip = closing :)
