### ISSUE TITLE
SideEffect timeout refund transaction causes panic

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#433]
There seems to be an issue with the refund transaction after the timeout. I have not been able to pinpoint what exactly is causing this, as it only happens sometimes. When appearing it creates a panic on every new block, failing to refund the assets of a SideEffect. This seems to haveonce SideEffects where executed on 2 different chains, but that could be a coincidence.

This seems to be very annoying to reproduce, but I will update this issue once I take a closer look/run into it again.

**Comment by petscheit** [comment]
====================

Version: 1.0.0-alpha.0-3ddf446f-aarch64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/capture.rs:140:22
   4: sp_panic_handler::panic_hook
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/panic-handler/src/lib.rs:166:18
   5: sp_panic_handler::set::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/panic-handler/src/lib.rs:62:12
   6: std::panicking::rust_panic_with_hook
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:610:17
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:502:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
   9: rust_begin_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
  10: core::panicking::panic_fmt
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
  11: core::result::unwrap_failed
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/result.rs:1613:5
  12: core::result::Result<T,E>::expect
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/result.rs:1255:23
  13: pallet_circuit::<impl pallet_circuit::pallet::Pallet<T>>::kill
             at /Users/paul/Documents/projects/t3rn/pallets/circuit/src/lib.rs:1461:9
  14: <pallet_circuit::pallet::Pallet<T> as frame_support::traits::hooks::Hooks<<T as frame_system::pallet::Config>::BlockNumber>>::on_initialize::{{closure}}
             at /Users/paul/Documents/projects/t3rn/pallets/circuit/src/lib.rs:359:25
  15: core::option::Option<T>::map
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/option.rs:846:29
  16: <pallet_circuit::pallet::Pallet<T> as frame_support::traits::hooks::Hooks<<T as frame_system::pallet::Config>::BlockNumber>>::on_initialize
             at /Users/paul/Documents/projects/t3rn/pallets/circuit/src/lib.rs:343:17
  17: <pallet_circuit::pallet::Pallet<T> as frame_support::traits::hooks::OnInitialize<<T as frame_system::pallet::Config>::BlockNumber>>::on_initialize
             at /Users/paul/Documents/projects/t3rn/pallets/circuit/src/lib.rs:323:15
  18: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  19: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  20: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  21: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  22: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  23: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  24: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  25: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  26: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  27: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  28: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  29: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  30: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  31: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  32: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  33: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  34: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  35: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  36: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/support/src/traits/hooks.rs:41:1
  37: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::initialize_block_impl
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/executive/src/lib.rs:307:34
  38: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::initialize_block
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/executive/src/lib.rs:279:3
  39: <circuit_standalone_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,circuit_standalone_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_non_zero_sender::CheckNonZeroSender<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_spec_version::CheckSpecVersion<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<circuit_standalone_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<circuit_standalone_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<circuit_standalone_runtime::Runtime>)>>>>::initialize_block
             at /Users/paul/Documents/projects/t3rn/runtime/standalone/src/lib.rs:396:13
  40: sp_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/api/src/lib.rs:660:1
  41: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call::{{closure}}::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/client/call_executor.rs:271:29
  42: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:595:61
  43: std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
  44: <unknown>
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:434:6
  45: std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
  46: std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
  47: sc_executor::native_executor::with_externalities_safe::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:65:3
  48: environmental::using::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:125:3
  49: std::thread::local::LocalKey<T>::try_with
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/local.rs:399:16
  50: std::thread::local::LocalKey<T>::with
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/local.rs:375:9
  51: environmental::using
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:106:2
  52: sp_externalities::scope_limited::ext::using
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:252:5
  53: sp_externalities::scope_limited::set_and_run_with_externalities
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/externalities/src/scope_limited.rs:31:2
  54: sc_executor::native_executor::with_externalities_safe
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:61:2
  55: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:595:17
  56: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:199:5
  57: sc_executor::wasm_runtime::VersionedRuntime::with_instance
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/wasm_runtime.rs:103:18
  58: sc_executor::wasm_runtime::RuntimeCache::with_instance
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/wasm_runtime.rs:285:6
  59: sc_executor::native_executor::WasmExecutor<H>::with_instance
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:189:9
  60: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/executor/src/native_executor.rs:559:16
  61: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/state-machine/src/lib.rs:428:31
  62: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/state-machine/src/lib.rs:546:46
  63: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/client/call_executor.rs:269:5
  64: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/client/client.rs:1687:3
  65: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/api/src/lib.rs:660:1
  66: <circuit_standalone_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl::{{closure}}
             at /Users/paul/Documents/projects/t3rn/runtime/standalone/src/lib.rs:385:1
  67: circuit_standalone_runtime::RuntimeApiImpl<Block,C>::call_api_at
             at /Users/paul/Documents/projects/t3rn/runtime/standalone/src/lib.rs:385:1
  68: <circuit_standalone_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
             at /Users/paul/Documents/projects/t3rn/runtime/standalone/src/lib.rs:385:1
  69: sp_api::Core::initialize_block_with_context
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/primitives/api/src/lib.rs:660:1
  70: sc_block_builder::BlockBuilder<Block,A,B>::new
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/block-builder/src/lib.rs:186:3
  71: <sc_service::client::client::Client<B,E,Block,RA> as sc_block_builder::BlockBuilderProvider<B,Block,sc_service::client::client::Client<B,E,Block,RA>>>::new_block_at
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/client/client.rs:1367:3
  72: sc_basic_authorship::basic_authorship::Proposer<B,Block,C,A,PR>::propose_with::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/basic-authorship/src/basic_authorship.rs:351:4
  73: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/future/mod.rs:80:19
  74: <sc_basic_authorship::basic_authorship::Proposer<B,Block,C,A,PR> as sp_consensus::Proposer<Block>>::propose::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/basic-authorship/src/basic_authorship.rs:308:15
  75: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/future/mod.rs:80:19
  76: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/future/future.rs:119:9
  77: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/task_manager/prometheus_future.rs:61:3
  78: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panic/unwind_safe.rs:289:9
  79: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/catch_unwind.rs:36:42
  80: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panic/unwind_safe.rs:271:9
  81: std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
  82: <unknown>
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:434:6
  83: std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
  84: std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
  85: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/catch_unwind.rs:36:9
  86: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/future/future.rs:119:9
  87: futures_util::future::future::FutureExt::poll_unpin
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/mod.rs:562:9
  88: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/select.rs:105:36
  89: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/task_manager/mod.rs:145:11
  90: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/future/mod.rs:80:19
  91: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  92: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  93: tokio::coop::with_budget::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  94: std::thread::local::LocalKey<T>::try_with
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/local.rs:399:16
  95: std::thread::local::LocalKey<T>::with
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/local.rs:375:9
  96: tokio::coop::with_budget
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
      tokio::coop::budget
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
      tokio::park::thread::CachedParkThread::block_on
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  97: tokio::runtime::enter::Enter::block_on
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  98: tokio::runtime::handle::Handle::block_on
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/handle.rs:355:9
  99: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /Users/paul/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/client/service/src/task_manager/mod.rs:172:6
 100: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
 101: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
 102: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
 103: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
 104: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
 105: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panic/unwind_safe.rs:271:9
 106: std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
 107: <unknown>
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:434:6
 108: std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
 109: std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
 110: tokio::runtime::task::harness::poll_future
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
 111: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
 112: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
 113: tokio::runtime::task::raw::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
 114: tokio::runtime::task::raw::RawTask::poll
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
 115: tokio::runtime::task::UnownedTask<S>::run
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
 116: tokio::runtime::blocking::pool::Task::run
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
 117: tokio::runtime::blocking::pool::Inner::run
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
 118: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
 119: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:123:18
 120: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/mod.rs:484:17
 121: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panic/unwind_safe.rs:271:9
 122: std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
 123: <unknown>
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/result.rs:1903:6
 124: std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
 125: std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
 126: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/thread/mod.rs:483:30
 127: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/ops/function.rs:227:5
 128: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys/unix/thread.rs:106:17
 129: _pthread_from_mach_thread_np


Thread 'tokio-runtime-worker' panicked at 'Panic: apply triggered by panic should never fail: RefundTransferFailed', /Users/paul/Documents/projects/t3rn/pallets/circuit/src/lib.rs:1462

This is a bug. Please report it at:

	support.anonymous.an

2022-08-29 21:28:36 🙌 Starting consensus session on top of parent 0x19aecb89f0718e4f0c4b1bfa2992e10793f00db4ea2a9e21c502b4777b235755
2022-08-29 21:28:36 Proposing failed: Import failed: Error at calling runtime api: Execution failed: Runtime panicked: Panic: apply triggered by panic should never fail: RefundTransferFailed

**Comment by petscheit** [comment]
Error just appeared again. It appears there might be a connection to me having the chain running, but the laptop closed.
